package nvdla


class nocifConfiguration extends project_spec{

  val RDMA_MAX_NUM = 10
  val WDMA_MAX_NUM = 5
  val WDMA_NUM = 8

  val FV_RAND_WR_PAUSE = false

  var RDMA_NUM = 0
  if(NVDLA_SDP_BS_ENABLE) {RDMA_NUM += 1}
  if(NVDLA_SDP_BN_ENABLE) {RDMA_NUM += 1}
  if(NVDLA_SDP_EW_ENABLE) {RDMA_NUM += 1}
  if(NVDLA_PDP_ENABLE)    {RDMA_NUM += 1}
  if(NVDLA_CDP_ENABLE)    {RDMA_NUM += 1}
  if(NVDLA_RUBIK_ENABLE)  {RDMA_NUM += 1}
  if(NVDLA_BDMA_ENABLE)   {RDMA_NUM += 1}

  val NVDLA_DMA_RD_IG_PW = NVDLA_MEM_ADDRESS_WIDTH+11
  val NVDLA_DMA_WR_IG_PW = NVDLA_MEM_ADDRESS_WIDTH+13

  val NVDLA_PRIMARY_MEMIF_STRB = NVDLA_MEMORY_ATOMIC_SIZE
}

